config/routes.rb
Casesavvy::Application.routes.draw do
  
  get 'test' => 'pages#test'
  get 'exhibitions' => 'pages#exhibitions'
  get 'about' => 'pages#about2'
  root :to => 'pages#home'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class = "footer">
	<small>
		<%= link_to "Wherever", "#" %>
		by Ashwin Muthiah
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <%= link_to "Boylan-Art", root_path, class: "brand"%>
    <ul class="nav">
    	<p class="navbar-text">
      	<li><%= link_to "Home", root_path %></li>
      	<li><%= link_to "About", about_path %></li>
      </p>
    </ul>
  </div>
</div>

app/views/layouts/_header2.html.erb
<div class="header">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
   
        <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
   
        <!-- Be sure to leave the brand out there if you want it shown -->
        <%= link_to "Boylan-Art", root_path, class: "brand" %>
   
        <!-- Everything you want hidden at 940px or less, place within here -->
        <div class="nav-collapse collapse">
        	<ul class = "nav">
            <p class="navbar-text">
          	  <li><%= link_to "Home", root_path %></li>
  					  <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Exhibitions", exhibitions_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Dummy Dropdown
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Home", root_path %></li>
                  <li><%= link_to "About", about_path %></li>
                  <li><%= link_to "Test", test_path %></li>  
                </ul>
              </li>
            </p>
  				</ul>
  				<ul class="nav pull-right">
            <li><%= link_to "kimberlysavannahboylan", root_path, class: "ksb" %></li>
          </ul>
        </div>
   
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Boylan-Art</title>
		  <%= stylesheet_link_tag    "application", :media => "all" %>
		  <%= javascript_include_tag "application" %>
		  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header2' %>
		<div class = "container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/pages/_ex.html.erb
<td><div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
<div class="carousel-inner">
      <div class="item active">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-01.jpg" width="100%">
        <div class="carousel-caption">
          <h4>First label</h4>
          <p>A working Bootstrap carousel example.</p>
        </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-02.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Second label</h4>
          <p>This is the second slide text.</p>
          </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-03.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Third label</h4>
          <p>Take note of the 'active' and 'slide' classes.</p>
        </div>
      </div>
    </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
</td>

app/views/pages/about.html.erb
<h1>About the Artist</h1>


<div class="about">
	<div class="box">
		<img src="savvy.jpg" />
		<div class = "abouttext">
		Boylan began her career portraying a most basic element, a necessary substance to survive in an extravagant light, giving food the spotlight it well deserves.
		</div>	
	</div>
</div>

app/views/pages/about2.html.erb
<h1>About the Artist</h1>

<div class="well">
	<div class="container-fluid">
	  <div class="row-fluid">
	    <div class="span3">
	      <%#img src="savvy.jpg", class="img-rounded"/%>
	      <%# in box tag to give it style - try taking it out if looks bad %>
	      <div class = "box">
	      <%= link_to (image_tag("https://s3.amazonaws.com/boylan-art/savvy.JPG")), root_path, class: "img-rounded" %>
	    </div>
	    </div>
	    <div class="span9">
	      Boylan began her career portraying a most basic element, a necessary substance to survive in an extravagant light, giving food the spotlight it well deserves.
	    </div>
	  </div>
	</div>
</div>

app/views/pages/exhibitions.html.erb
<h3>Welcome to the Exhibitions Page</h3>

<table class="table">
	<tr>
		<td>
			<h5><%= link_to "Abstract", '#', class: "btn" %></h5>
			<p>This exhibition contains the abstract pieces of artwork that Boylan has been painting in recent years.</p>
		</td>
		<td><div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
<div class="carousel-inner">
      <div class="item active">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-01.jpg" width="100%">
        <div class="carousel-caption">
          <h4>First label</h4>
          <p>A working Bootstrap carousel example.</p>
        </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-02.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Second label</h4>
          <p>This is the second slide text.</p>
          </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-03.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Third label</h4>
          <p>Take note of the 'active' and 'slide' classes.</p>
        </div>
      </div>
    </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
		</td>
	</tr>	
	<tr>
		<td>
			<h5><%= link_to "Food", '#', class: "btn" %></h5>
			<p>This exhibition contains the pieces of art with food-centric focus. The pieces are meant to invoke a deep sense of questioning: do we take for granted what we need most to survive?</p>
		</td>
		<td><div id="myCarousel1" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel1" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel1" data-slide-to="1"></li>
    <li data-target="#myCarousel1" data-slide-to="2"></li>
  </ol>
<div class="carousel-inner">
      <div class="item active">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-01.jpg" width="100%">
        <div class="carousel-caption">
          <h4>First label</h4>
          <p>A working Bootstrap carousel example.</p>
        </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-02.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Second label</h4>
          <p>This is the second slide text.</p>
          </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-03.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Third label</h4>
          <p>Take note of the 'active' and 'slide' classes.</p>
        </div>
      </div>
    </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel1" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel1" data-slide="next">&rsaquo;</a>
</div>
		</td>
	</tr>
</tbody>
</table>

app/views/pages/home.html.erb
<div class = "homepadding">
	<div class = "hero-unit">
		<h1>Boylan-Art</h1>

		<p>Enter the Gallery to see the works of renowned artist, Kimberly Savannah Boylan.
		</p>

		<p>
			<%= link_to "Enter the Gallery", exhibitions_path, class: "btn btn-primary" %>
		</p>


	</div>
</div>

app/views/pages/test.html.erb
<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
<div class="carousel-inner">
      <div class="item active">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-01.jpg" width="100%">
        <div class="carousel-caption">
          <h4>First label</h4>
          <p>A working Bootstrap carousel example.</p>
        </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-02.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Second label</h4>
          <p>This is the second slide text.</p>
          </div>
      </div>
      <div class="item">
        <img src="//twitter.github.io/bootstrap/assets/img/bootstrap-mdo-sfmoma-03.jpg" width="100%">
        <div class="carousel-caption">
          <h4>Third label</h4>
          <p>Take note of the 'active' and 'slide' classes.</p>
        </div>
      </div>
    </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>